## Window and Workspace rules

# Multi-monitor workspace rules
workspace = 1, monitor:DP-3
workspace = 2, monitor:DP-3
workspace = 3, monitor:DP-3
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1, on-created-empty: rhythmbox
workspace = 6, monitor:eDP-1
workspace = special:scratchpad, on-created-empty:[float] kitty

# Empty workspaces
workspace = 16, monitor:DP-3
workspace = 17, monitor:DP-2
workspace = 18, monitor:eDP-1

## Window Rules

windowrule {
    name = Float windows
    match:class = (imv)|(org.gnome.FileRoller)|(file-roller)|(zenity)|(^$)|(ffplay)
    float = on
}
windowrule = match:class .*hunar,   opacity 0.9
windowrule = match:class .*hunar,   float on

# User-specific applications
windowrule = match:class librewolf, workspace 1
windowrule = match:initial_title Picture-in-Picture, float on
windowrule = match:class code, workspace 3
windowrule = match:class Godot, workspace 3
windowrule = match:class Godot, tile on
windowrule = match:class PlaydateSimulator, float on
windowrule {
    name = Blender
    match:class = blender
    workspace = 3
    float = on
    size = 80% 80%
    center = on
}
windowrule = match:class .blueman-manager-wrapped, workspace special:scratchpad
windowrule = match:class com.obsproject.Studio, workspace special:scratchpad silent
windowrule = match:title Nextcloud, float on

# Games
windowrule = match:class steam, workspace 2 silent
windowrule = match:class steam_app_.*, workspace 3
windowrule = match:class steam_app_.*, fullscreen on
windowrule = match:class lunarclient, workspace 2
windowrule = match:class Lunar Client.*, workspace 3
windowrule = match:class Lunar Client.*, fullscreen on
windowrule = match:class org.prismlauncher.PrismLauncher, workspace 2
windowrule = match:class ^(Minecraft)(.*)$, workspace 3
windowrule = match:class ^(Minecraft)(.*)$, fullscreen on
windowrule = match:class osu!, workspace 3

windowrule = match:class obsidian,          workspace 2
windowrule = match:title Save File,         float on
windowrule = match:class vesktop,           workspace 4 silent
windowrule = match:class vesktop,           opacity 0.9
windowrule = match:class Open Files,        float on # File chooser
windowrule = match:title https://discord.com/.*,  float on # Download options
windowrule = match:title Vencord QuickCSS Editor, float on
windowrule = match:class rhythmbox,         workspace 5 silent
windowrule = match:class thunderbird,       workspace 6
windowrule {
    name = Thunderbird popups
    match:class = thunderbird
    match:title = negative:Mozilla Thunderbird
    float = on
}

windowrule = match:class .*, suppress_event maximize
windowrule = match:fullscreen 1, opacity 1

# Autostart applications
exec-once = hyprctl dispatch workspace 3 # start on workspace 3
exec-once = sleep 2.2 && vesktop
exec-once = [workspace 6 silent] thunderbird
exec-once = sleep 2.2 && nextcloud
