splash = false

# Laptop display
wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/galaxy.png
}

# Secondary monitors
wallpaper {
    monitor = 
    path = ~/Pictures/Wallpapers/galaxy-secondary.png
}

